feat: New Output Plugin Microsoft Fabric
asaharn/telegraf pull request #4
Opened 2024-09-13 18:17 UTC by Abhishek-saharn

## Summary

## Checklist

- [ ] No AI generated code was used in this PR

## Related issues

resolves #

2024-10-15 08:22 UTC, ag-ramachandran requested changes

2024-10-15 08:22 UTC, ag-ramachandran commented on plugins/outputs/microsoft_fabric/sample.conf
> +        ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
CI needs passing, looks like semantic naming conventions have to be followed

2024-10-16 14:37 UTC, asaharn commented on plugins/outputs/microsoft_fabric/microsoft_fabric.go
> +				Timeout:      config.Duration(20 * time.Second),
Yes. Timeout is configurable. this is default. as per the corresponding connector.

2024-10-16 15:22 UTC, asaharn commented
Moved change to https://github.com/asaharn/telegraf/pull/5

2024-10-16 15:22 UTC, closed without merging