feat: New Output Plugin Microsoft Fabric
asaharn/telegraf pull request #5
Opened 2024-10-16 15:21 UTC by asaharn

## Summary

## Checklist

- [ ] No AI generated code was used in this PR

## Related issues

resolves #

2024-10-18 05:06 UTC, ag-ramachandran requested changes

2024-10-18 05:06 UTC, ag-ramachandran commented on plugins/outputs/microsoft_fabric/microsoft_fabric.go
> +		return errors.New("endpoint must not be empty. For Kusto refer : https://learn.microsoft.com/kusto/api/connection-strings/kusto?view=microsoft-fabric for EventStream refer : https://learn.microsoft
For EventHouse refer

2024-10-18 05:06 UTC, ag-ramachandran commented on plugins/outputs/microsoft_fabric/microsoft_fabric.go
> +		return errors.New("invalid connection string. Connection string must start with 'Endpoint=sb' for EventHub or 'https://' for Kusto")
Actually it is DataSource = and not https://, better to have error copied from line 52 (except for ConnectionString is empty part)

2024-10-18 05:06 UTC, ag-ramachandran commented on plugins/outputs/microsoft_fabric/microsoft_fabric.go
> +	} else if strings.HasPrefix(ConnectionString, "https://") {
I think it is DataSource= IIRC

2024-10-18 05:06 UTC, ag-ramachandran commented on plugins/outputs/microsoft_fabric/microsoft_fabric_test.go
> +	err := mf.Init()
Tests for ConnectionString for SB and EventHouse too

2024-10-18 05:06 UTC, ag-ramachandran commented on plugins/outputs/microsoft_fabric/microsoft_fabric.go
> +				CreateTables: true,
We have to have a mechanism where we can say this is from Fabric (To split the traffic) based on AppId to see usage for this connector as well. We probably have to make a fix in the connector for Kusto first to accept AppName as a parameter and then pass it in from here as well ?

2025-01-02 04:49 UTC, asaharn commented
new PR raised #7

2025-01-02 04:49 UTC, closed without merging